development:
   secret_key_base: '4fb34c831593269e915'
   image_secret_hash: '73156bef2884bfad0c823bd1816'
   devise_secret_key: 'f2bec73156bef2884bfa'
   s3_access_key_id: 'some_secret_access_key_id'
   s3_secret_access_key: 'some_secret_access_key'
   s3_bucket: 'some_dev_bucket'

test:
   secret_key_base: '80eeca21c8e0becb16f'
   image_secret_hash: '73156bef2884bfad0c823bd1816'
   devise_secret_key: 'e805e79967aa0b2aa320'

production:
   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
   image_secret_hash: <%= ENV["IMAGE_SECRET_HASh"] %>
   devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
   s3_access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
   s3_secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
   s3_bucket: <%= ENV["S3_BUCKET"] %>
