class Food < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 150 }, allow_blank: false
  validates :serving_size, presence: true, length: { minimum: 1, maximum: 75 }
  validates_numericality_of :calories, 
                            :calories_from_fat,
                            :total_fat,
                            :saturated_fat,
                            :trans_fat,
                            :polyunsaturated_fat,
                            :monounsaturated_fat,
                            :cholesterol,
                            :sodium,
                            :carbs,
                            :dietary_fiber,
                            :sugars,
                            :protein,
                            :vitamin_a,
                            :vitamin_c,
                            :calcium,
                            :iron,
                            :vitamin_d,
                            :vitamin_e,
                            :vitamin_k,
                            :thiamin,
                            :riboflavin,
                            :niacin,
                            :vitamin_b6,
                            :biotin,
                            :pantothenic_acid,
                            :phosphorus,
                            :iodine,
                            :magnesium,
                            :zinc,
                            :selenium,
                            :copper,
                            :manganese,
                            :chromium,
                            :molybednum,
                            :caffeine,
                            :alcohol,
                            :potassium,
                            :folic_acid,
                            :boron,
                            :cobalt,
                            :fluoride,
                            :acetic_acid,
                            :citric_acid,
                            :lactic_acid,
                            :malic_acid,
                            :choline,
                            :taurine,
                            :glutamine,
                            :creatine,
                            :sugar_alcohols,
                            :chloride,
                            greater_than_or_equal_to: 0
end
